import type { DomainPack } from "./types.ts";

export const softwareDomainPack: DomainPack = {
  id: "software",
  version: "1.0.0",
  displayName: "Software Engineering",
  intents: [
    {
      id: "implement_feature",
      description: "Implement a requested software feature with tests and documentation.",
      examples: ["新增 CLI 指令 calc sum", "implement a parser option and tests"],
      workflowTemplateRef: "software-feature-template",
      requiredInputs: ["goalPrompt", "repoPath"],
      defaultContextPolicyRef: "software-context-default",
      defaultSessionPolicyRef: "software-session-default",
    },
    {
      id: "fix_bug",
      description: "Investigate and fix a failing behavior.",
      examples: ["修正 test failure", "fix calc add bug"],
      workflowTemplateRef: "software-feature-template",
      requiredInputs: ["goalPrompt", "repoPath"],
      defaultContextPolicyRef: "software-context-default",
      defaultSessionPolicyRef: "software-session-default",
    },
  ],
  roles: [
    {
      id: "explorer",
      responsibility: "Inspect the repository and create an implementation plan.",
      defaultAgentProfileRef: "software-explorer-codex",
      allowedAgentProfileRefs: ["software-explorer-codex", "software-explorer-pi"],
      artifactInputs: [],
      artifactOutputs: ["implementation_plan"],
      stopAuthority: "none",
    },
    {
      id: "maker",
      responsibility: "Edit the workspace and produce implementation evidence.",
      defaultAgentProfileRef: "software-maker-pi",
      allowedAgentProfileRefs: ["software-maker-pi"],
      artifactInputs: ["implementation_plan"],
      artifactOutputs: ["implementation_report"],
      stopAuthority: "none",
    },
    {
      id: "checker",
      responsibility: "Verify tests, diff, evidence, and policy compliance.",
      defaultAgentProfileRef: "software-checker-codex",
      allowedAgentProfileRefs: ["software-checker-codex", "software-checker-pi"],
      artifactInputs: ["implementation_report"],
      artifactOutputs: ["verification_report"],
      stopAuthority: "can-reject",
    },
    {
      id: "summarizer",
      responsibility: "Produce the final completion report after acceptance.",
      defaultAgentProfileRef: "software-summarizer-codex",
      allowedAgentProfileRefs: ["software-summarizer-codex"],
      artifactInputs: ["implementation_report", "verification_report"],
      artifactOutputs: ["completion_report"],
      stopAuthority: "can-accept",
    },
  ],
  agentProfiles: [
    {
      id: "software-explorer-codex",
      name: "Software Explorer",
      provider: "codex",
      model: "gpt-5-codex",
      harnessRef: "codex",
      agentsMdRefs: ["repo:AGENTS.md"],
      promptTemplateRef: "software-explorer",
      skillRefs: ["software.calc-cli"],
      mcpGrantRefs: [],
      memoryScopes: ["software", "project"],
      contextPolicyRef: "software-context-default",
      sessionPolicyRef: "software-session-default",
      toolPolicy: { allowedTools: ["read", "search"], deniedTools: ["write"], requiresApprovalFor: [] },
      budgetPolicy: { maxInputTokens: 12_000, maxOutputTokens: 2_000, maxWallTimeSeconds: 300 },
    },
    {
      id: "software-explorer-pi",
      name: "Software Explorer Pi",
      provider: "pi",
      model: "pi-agent-default",
      harnessRef: "pi",
      agentsMdRefs: ["repo:AGENTS.md"],
      promptTemplateRef: "software-explorer",
      skillRefs: ["software.calc-cli"],
      mcpGrantRefs: [],
      memoryScopes: ["software", "project"],
      contextPolicyRef: "software-context-default",
      sessionPolicyRef: "software-session-default",
      toolPolicy: { allowedTools: ["read", "search"], deniedTools: ["write"], requiresApprovalFor: [] },
      budgetPolicy: { maxInputTokens: 12_000, maxOutputTokens: 2_000, maxWallTimeSeconds: 300 },
    },
    {
      id: "software-maker-pi",
      name: "Software Maker Pi",
      provider: "pi",
      model: "pi-agent-default",
      harnessRef: "pi",
      agentsMdRefs: ["repo:AGENTS.md"],
      promptTemplateRef: "software-maker",
      skillRefs: ["software.calc-cli"],
      mcpGrantRefs: ["filesystem-workspace"],
      memoryScopes: ["software", "project"],
      contextPolicyRef: "software-context-default",
      sessionPolicyRef: "software-session-default",
      toolPolicy: {
        allowedTools: ["read", "search", "edit", "shell"],
        deniedTools: ["network-write"],
        requiresApprovalFor: ["external-write"],
      },
      budgetPolicy: { maxInputTokens: 20_000, maxOutputTokens: 4_000, maxWallTimeSeconds: 900 },
    },
    {
      id: "software-checker-codex",
      name: "Software Checker",
      provider: "codex",
      model: "gpt-5-codex",
      harnessRef: "codex",
      agentsMdRefs: ["repo:AGENTS.md"],
      promptTemplateRef: "software-checker",
      skillRefs: ["software.calc-cli"],
      mcpGrantRefs: [],
      memoryScopes: ["software", "project"],
      contextPolicyRef: "software-context-default",
      sessionPolicyRef: "software-session-default",
      toolPolicy: { allowedTools: ["read", "search", "shell"], deniedTools: ["edit"], requiresApprovalFor: [] },
      budgetPolicy: { maxInputTokens: 16_000, maxOutputTokens: 3_000, maxWallTimeSeconds: 600 },
    },
    {
      id: "software-checker-pi",
      name: "Software Checker Pi",
      provider: "pi",
      model: "pi-agent-default",
      harnessRef: "pi",
      agentsMdRefs: ["repo:AGENTS.md"],
      promptTemplateRef: "software-checker",
      skillRefs: ["software.calc-cli"],
      mcpGrantRefs: [],
      memoryScopes: ["software", "project"],
      contextPolicyRef: "software-context-default",
      sessionPolicyRef: "software-session-default",
      toolPolicy: { allowedTools: ["read", "search", "shell"], deniedTools: ["edit"], requiresApprovalFor: [] },
      budgetPolicy: { maxInputTokens: 16_000, maxOutputTokens: 3_000, maxWallTimeSeconds: 600 },
    },
    {
      id: "software-summarizer-codex",
      name: "Software Summarizer",
      provider: "codex",
      model: "gpt-5-codex",
      harnessRef: "codex",
      agentsMdRefs: [],
      promptTemplateRef: "software-summarizer",
      skillRefs: [],
      mcpGrantRefs: [],
      memoryScopes: ["software", "project"],
      contextPolicyRef: "software-context-summary",
      sessionPolicyRef: "software-session-default",
      toolPolicy: { allowedTools: ["read"], deniedTools: ["edit", "shell"], requiresApprovalFor: [] },
      budgetPolicy: { maxInputTokens: 8_000, maxOutputTokens: 2_000, maxWallTimeSeconds: 180 },
    },
  ],
  workflowTemplates: [
    {
      id: "software-feature-template",
      intentRefs: ["implement_feature", "fix_bug"],
      stages: [
        {
          id: "understand",
          roleRef: "explorer",
          dependsOn: [],
          promptTemplateRef: "software-explorer",
          requiredArtifactRefs: ["implementation_plan"],
          evaluatorPipelineRef: "software-plan-quality",
          stopConditionRefs: [],
          workspacePolicyRef: "software-git-workspace",
          allowDynamicExpansion: true,
        },
        {
          id: "implement",
          roleRef: "maker",
          dependsOn: ["understand"],
          promptTemplateRef: "software-maker",
          requiredArtifactRefs: ["implementation_report"],
          evaluatorPipelineRef: "software-feature-quality",
          stopConditionRefs: [],
          workspacePolicyRef: "software-git-workspace",
          allowDynamicExpansion: true,
        },
        {
          id: "verify",
          roleRef: "checker",
          dependsOn: ["implement"],
          promptTemplateRef: "software-checker",
          requiredArtifactRefs: ["verification_report"],
          evaluatorPipelineRef: "software-verification-quality",
          stopConditionRefs: ["software-feature-complete"],
          workspacePolicyRef: "software-git-workspace",
          allowDynamicExpansion: true,
        },
        {
          id: "summarize",
          roleRef: "summarizer",
          dependsOn: ["verify"],
          promptTemplateRef: "software-summarizer",
          requiredArtifactRefs: ["completion_report"],
          evaluatorPipelineRef: "software-completion-quality",
          stopConditionRefs: ["software-feature-complete"],
          workspacePolicyRef: "software-git-workspace",
          allowDynamicExpansion: false,
        },
      ],
    },
  ],
  workflowGeneratorPolicies: [
    {
      id: "software-feature-generator",
      intentRefs: ["implement_feature", "fix_bug"],
      templateRefs: ["software-feature-template"],
      allowedRoleRefs: ["explorer", "maker", "checker", "summarizer"],
      allowedAgentProfileRefs: [
        "software-explorer-codex",
        "software-explorer-pi",
        "software-maker-pi",
        "software-checker-codex",
        "software-checker-pi",
        "software-summarizer-codex",
      ],
      allowedEvaluatorPipelineRefs: [
        "software-plan-quality",
        "software-feature-quality",
        "software-verification-quality",
        "software-completion-quality",
      ],
      allowedArtifactContractRefs: ["implementation_plan", "implementation_report", "verification_report", "completion_report"],
      maxTasks: 8,
      maxParallelTasks: 3,
      maxAgentInvocations: 12,
      maxEstimatedInputTokens: 80_000,
      maxEstimatedCostMicrosUsd: 500_000,
      qualityPatterns: ["maker-checker", "fanout-fanin", "rollback-on-test-failure", "fork-on-checker-reject"],
    },
  ],
  artifactContracts: [
    {
      id: "implementation_plan",
      artifactType: "implementation-plan",
      requiredFields: ["summary", "filesToInspect", "commandsToRun", "risks"],
      evidenceFields: ["filesToInspect", "commandsToRun"],
    },
    {
      id: "implementation_report",
      artifactType: "implementation-report",
      requiredFields: ["summary", "filesChanged", "commandsRun", "testResults", "risks", "artifactEvidence"],
      evidenceFields: ["filesChanged", "commandsRun", "testResults", "artifactEvidence"],
    },
    {
      id: "verification_report",
      artifactType: "verification-report",
      requiredFields: ["summary", "commandsRun", "testResults", "checkerFindings", "risks"],
      evidenceFields: ["commandsRun", "testResults", "checkerFindings"],
    },
    {
      id: "completion_report",
      artifactType: "completion-report",
      requiredFields: ["summary", "acceptedArtifacts", "tests", "risks", "followUps"],
      evidenceFields: ["acceptedArtifacts", "tests"],
    },
  ],
  evaluatorPipelines: [
    {
      id: "software-plan-quality",
      evaluators: [{ id: "schema", kind: "schema", config: { artifactRef: "implementation_plan" }, required: true }],
      onFailure: { defaultStrategy: "retry-same-agent" },
    },
    {
      id: "software-feature-quality",
      evaluators: [
        { id: "schema", kind: "schema", config: { artifactRef: "implementation_report" }, required: true },
        { id: "evidence", kind: "evidence", config: { artifactRef: "implementation_report" }, required: true },
        { id: "tests", kind: "test", config: { command: "npm test" }, required: true },
        { id: "policy", kind: "policy", config: { denyExternalWrite: true }, required: true },
      ],
      onFailure: { defaultStrategy: "rollback-workspace" },
    },
    {
      id: "software-verification-quality",
      evaluators: [
        { id: "schema", kind: "schema", config: { artifactRef: "verification_report" }, required: true },
        { id: "checker", kind: "checker-agent", config: { artifactRef: "verification_report" }, required: true },
      ],
      onFailure: { defaultStrategy: "fork-from-checkpoint" },
    },
    {
      id: "software-completion-quality",
      evaluators: [{ id: "schema", kind: "schema", config: { artifactRef: "completion_report" }, required: true }],
      onFailure: { defaultStrategy: "request-workflow-revision" },
    },
  ],
  contextPolicies: [
    {
      id: "software-context-default",
      maxInputTokens: 20_000,
      memoryPolicyRef: "software-memory-default",
      includeAgentsMd: true,
      includeWorkspaceSummary: true,
    },
    {
      id: "software-context-summary",
      maxInputTokens: 8_000,
      memoryPolicyRef: "software-memory-default",
      includeAgentsMd: false,
      includeWorkspaceSummary: false,
    },
  ],
  sessionPolicies: [
    {
      id: "software-session-default",
      checkpointOn: ["task-start", "artifact-accepted", "before-recovery"],
      allowFork: true,
      allowReset: true,
      allowRollback: true,
    },
  ],
  memoryPolicies: [
    {
      id: "software-memory-default",
      providerRef: "sqlite",
      scopes: ["software", "project"],
      maxInjectedTokens: 1_500,
      maxCandidates: 8,
      requireWriteApproval: true,
      allowedKinds: [
        "preference",
        "architecture_decision",
        "domain_pattern",
        "failure_lesson",
        "artifact_summary",
        "workflow_learning",
      ],
      ranking: { relevanceWeight: 0.55, recencyWeight: 0.15, successWeight: 0.2, confidenceWeight: 0.1 },
      compression: { strategy: "extractive", maxTokensPerMemory: 240 },
    },
  ],
  workspacePolicies: [
    {
      id: "software-git-workspace",
      provider: "git",
      snapshotAtTaskStart: true,
      snapshotAtAcceptedArtifact: true,
      forkOnCheckerReject: true,
      rollbackOnTestFailure: true,
    },
  ],
  stopConditions: [
    {
      id: "software-feature-complete",
      type: "custom",
      evaluatorRefs: ["software-feature-quality", "software-verification-quality", "software-completion-quality"],
    },
  ],
};
